# Generated by Django 4.2.7 on 2025-09-10 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('university', 'University'), ('research_institute', 'Research Institute'), ('hospital', 'Hospital'), ('ngo', 'NGO'), ('government', 'Government Agency')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Research Categories',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('is_principal_investigator', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('study_type', models.CharField(choices=[('rct', 'Randomized Controlled Trial'), ('cohort', 'Cohort Study'), ('cross_sectional', 'Cross-sectional Study'), ('case_control', 'Case-control Study'), ('systematic_review', 'Systematic Review'), ('meta_analysis', 'Meta-analysis')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('pmid', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchcategory')),
                ('institutions', models.ManyToManyField(to='research.institution')),
            ],
            options={
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('studies', models.ManyToManyField(blank=True, to='research.researchstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('authors', models.TextField(help_text='Comma-separated list of authors')),
                ('journal', models.CharField(max_length=200)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, max_length=20)),
                ('publication_date', models.DateField()),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('pmid', models.CharField(blank=True, max_length=20)),
                ('abstract', models.TextField(blank=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.researchstudy')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='GeographicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('studies', models.ManyToManyField(blank=True, to='research.researchstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('spss', 'SPSS'), ('stata', 'Stata'), ('r', 'R Data'), ('json', 'JSON')], max_length=20)),
                ('size_mb', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchstudy')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('notebook_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='StudyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pi', 'Principal Investigator'), ('co_pi', 'Co-Principal Investigator'), ('investigator', 'Investigator'), ('co_investigator', 'Co-Investigator'), ('statistician', 'Statistician'), ('data_manager', 'Data Manager')], max_length=100)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researcher')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchstudy')),
            ],
            options={
                'unique_together': {('researcher', 'study')},
            },
        ),
    ]
